export const appRoutes = {
  root: "/",
  home: "/home",
  explore: "/explore",
  create: "/create",
  chat: "/chat",
  chatThread: "/chat/:conversationId",
  spaces: "/spaces",
  space: "/spaces/:spaceId",
  spaceChannel: "/spaces/:spaceId/:channelId",
  files: "/files",
  file: "/files/:fileId",
  profile: "/profile",
  profileUser: "/profile/:username",
  notifications: "/notifications",
  search: "/search",
  settings: "/settings",
  settingsAccount: "/settings/account",
  settingsPrivacy: "/settings/privacy",
  settingsNotifications: "/settings/notifications",
  settingsSecurity: "/settings/security",
  post: "/post/:postId",
  document: "/document/:fileId",
  media: "/media/:mediaId",
  login: "/login",
  signup: "/signup",
} as const;
